site_name: "python_tooling_enterpy_2021"
site_description: "A simple demo project"
dev_addr: localhost:9090

nav:
- Home:
    - Overview: index.md
- API Doc: api_doc.md

# https://python-markdown.github.io/extensions/
markdown_extensions:
- toc:
    permalink: True
- plantuml_markdown:
    server: http://www.plantuml.com/plantuml

plugins:
- search
- mkdocstrings:
    watch:
    - python_tooling_enterpy_2021
- gen-files:
    scripts:
    - docs/gen_api_doc.py